apiVersion: v1
kind: Service 
metadata:
  name: myapp1-lb-service-nlb
  annotations:
    # To create Network Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    external-dns.alpha.kubernetes.io/hostname: "nlb.eksinfra.com"
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: myapp1
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port