apiVersion: v1
kind: Service
metadata:
  name: usermgmt-webapp-nlb-service
  labels: 
    app: usermgmt-webapp
  annotations:
    # To create Network Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  # Default - CLB
  type: LoadBalancer
  selector:
    app: usermgmt-webapp
  ports: 
    - port: 80
      targetPort: 8080